server:
  port: 8089 #项目服务的端口号（如8089/8088等）
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mesmanager?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
#sql日志打印
logging:
  level:
    org.mybatis: debug
mybatis:
  config-location: classpath:config/mybatis/config/mysql/mybatis-frame.xml #mybatis配置文件源
  mapper-locations: classpath*:config/mybatis/mappers/mysql/**/*.xml #数据持久层文件源


