server:
  port: 8089
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mesmanager?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
# 新增图片上传路径配置
file:
  upload:
    base-path: MYWeb/MESProductWeb/src/main/webapp/images/productImg/
logging:
  level:
    org.mybatis: debug
mybatis:
  config-location: classpath:config/mybatis/config/mysql/mybatis-frame.xml
  mapper-locations: classpath*:config/mybatis/mappers/mysql/**/*.xml